name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - run: flutter config --enable-web

      - run: flutter pub get

      - name: Flutter test
        if: ${{ false }}
        run: flutter test

      - name: Build web
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAMUSHEK_SCHOODULE }}'
          channelId: live
          projectId: kamushek-schoodule
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
